update theme, rework css, disable hack css

diff --git a/themes/after-dark/bin/install b/themes/after-dark/bin/install
--- a/themes/after-dark/bin/install
+++ b/themes/after-dark/bin/install
@@ -1,55 +1,58 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
-function create_site() {
+validate_hugo () {
    # Exit with error if hugo is not installed
    if ! hash hugo 2>/dev/null ; then
      echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
    fi
 
    # Exit with error if not minimum required hugo version
-   local re='v(0\d*\.(([4-9][4-9]|[5-9]))|[1-9]).*'
-   if ! [[ $(hugo version) =~ $re ]] ; then
+   re="v(0\d*\.([4-9][4-9]|[5-9])|[1-9]).*"
+   if ! hugo version | grep -qE "$re" ; then
       echo "Error: After Dark requires Hugo version 0.44 or greater" >&2; exit 1
    fi
+}
 
-   # Create new hugo site at specified location
-   echo "Creating a new Hugo site ..."
-   if [ "$CONTINUE" = "y" ] ; then
-      hugo new site --force $SITE_DIR 1>/dev/null
-   else
-      hugo new site $SITE_DIR 1>/dev/null
+create_site_dir () {
+   SITE_DIR="flying-toasters"
+   if [ "$1" != "" ] ; then
+      SITE_DIR="$1"
    fi
-   cd "$SITE_DIR"
+
+   SITE_DIR_ABS="$PWD/$SITE_DIR"
+   mkdir -p "$SITE_DIR"
 }
 
-function download_theme() {
-   # Download latest version of After Dark theme
-   echo "Downloading the latest version of After Dark theme ..."
-   local v=$(wget -O - https://git.habd.as/comfusion/after-dark/raw/branch/master/package.json 2>&1 /dev/null | grep -o '"version"\s*:\s*.*",' | tr -d 'version": ,')
-   local t=$(mktemp)
-   wget https://git.habd.as/comfusion/after-dark/archive/v${v}.tar.gz -qO "$t"
-   tar -xzf "$t" -C themes
-   rm "$t"
-   echo "Theme version $v downloaded to $SITE_DIR/themes/after-dark"
+create_site () {
+   echo "Creating a new Hugo site ..."
+   hugo new site "$SITE_DIR" 1>/dev/null
+   cd "$SITE_DIR" || exit 1
 }
 
-function download_module() {
-   # Download latest version of Fractal Forest for After Dark theme
-   echo "Downloading Fractal Forest module for After Dark theme ..."
-   local v=$(wget -O - https://git.habd.as/comfusion/fractal-forest/raw/branch/master/package.json 2>&1 /dev/null | grep -o '"version"\s*:\s*.*",' | tr -d 'version": ,')
-   local t=$(mktemp)
-   wget https://git.habd.as/comfusion/fractal-forest/archive/v${v}.tar.gz -qO "$t"
-   tar -xzf "$t" -C themes
-   rm "$t"
-   echo "Module version $v downloaded to $SITE_DIR/themes/fractal-forest"
+download_theme () {
+   echo "Downloading the latest version of After Dark ..."
+   THEME_META=$(wget -qO - https://registry.npmjs.org/after-dark/latest)
+   vers=$(echo "$THEME_META" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   mkdir -p themes/after-dark
+   wget -qO - https://registry.npmjs.org/after-dark/-/after-dark-"$vers".tgz | tar --strip-components=1 -xz -C themes/after-dark
+   echo "Version $vers downloaded to $SITE_DIR/themes/after-dark"
 }
 
-function configure_theme() {
-   # Provide basic configuration and ignore generated files
+download_module () {
+   [ -z "$1" ] && { echo "Error: Attempt to download undefined module" >&2; exit 1; }
+   echo "Downloading $1 module for After Dark ..."
+   meta=$(wget -qO - https://registry.npmjs.org/"$1"/latest)
+   vers=$(echo "$meta" | egrep -o "\"version\".*[^,]*," | cut -d ',' -f1 | cut -d ':' -f2 | tr -d '" ')
+   mkdir -p themes/"$1"
+   wget -qO - https://registry.npmjs.org/"$1"/-/"$1"-"$vers".tgz | tar --strip-components=1 -xz -C themes/"$1"
+   echo "Version $vers downloaded to $SITE_DIR/themes/$1"
+}
+
+configure_theme () {
    echo "Configuring basic After Dark theme settings ..."
    tee "config.toml" > /dev/null <<TOML
-baseurl = "https://c74ce35e.ngrok.io/" # Controls base URL
+baseurl = "https://donate.habd.as" # Controls base URL sitewide
 languageCode = "en-US" # Controls site language
 title = "After Dark" # Homepage title and page title suffix
 paginate = 11 # Number of posts to show before paginating
@@ -61,9 +64,12 @@ theme = [
 ]
 
 enableRobotsTXT = true # Suggested, enable robots.txt file
-googleAnalytics = "" # Optional, add tracking Id for analytics
-disqusShortname = "" # Optional, add Disqus shortname for comments
-SectionPagesMenu = "main" # Enable menu system for lazy bloggers
+disqusShortname = "" # Deprecated, add Disqus shortname for comments
+
+pygmentsCodefences = true # Suggested, highlight fenced code blocks
+pygmentsUseClasses = true # Required for custom syntax highlighting
+
+sectionPagesMenu = "main" # Enable menu system for lazy bloggers
 footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
 
 [params]
@@ -71,15 +77,10 @@ footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
   author = "" # Optional, controls author name display on posts
   hide_author = true # Optional, set true to hide author name on posts
   show_menu = false # Optional, set true to enable section menu
-  powered_by = true # Optional, set false to disable credits
+  powered_by = true # Optional, set false to disable footer credits
   images = [
     "https://source.unsplash.com/collection/983219/2000x1322"
   ] # Suggested, controls default Open Graph images
-
-[params.hackcss]
-  disabled = false # Optional, set true to disable hackcss
-  mode = "hack" # Optional, choose from standard or hack display modes
-  palette = "dark" # Optional, choose from dark, dark-grey and solarized-dark
 
 [params.modules.fractal_forest]
   enabled = true # Optional, set false to disable module
@@ -87,52 +88,44 @@ footnoteReturnLinkContents = "↩" # Provides a nicer footnote return link
 TOML
 }
 
-function create_example_post() {
-   echo "Creating an example post to get you started ..."
-   hugo new post/starry-night.md 1>/dev/null
+update_archetypes () {
+   echo "Updating site default content archetype ..."
+   rm -f archetypes/default.md
+   cp themes/after-dark/archetypes/default.md archetypes
 }
 
-function serve_site_maybe() {
-   if hash elinks 2>/dev/null ; then
-      echo "Opening your new After Dark site in elinks ..."
-      hugo serve --buildDrafts --port 1337 --bind "0.0.0.0" 1>/dev/null &
-      sleep 1
-      elinks http://0.0.0.0:1337/
-   fi
+generate_help_docs () {
+   echo "Generating help documentation ..."
+   meta_path=themes/after-dark/data/npm
+   mkdir -p "$meta_path" && echo "$THEME_META" | tr '\r\n' ' ' > "$meta_path"/latest.json
+   hugo new help/index.md --kind help 1>/dev/null
 }
 
-function create_site_dir() {
-   local path=${1}
-   if [[ "$path" == "" ]] ; then
-      SITE_DIR="flying-toasters"
-   else
-      SITE_DIR="$path"
-   fi;
-
-   SITE_DIR_ABS="$PWD/$SITE_DIR"
-   if [ -d "$SITE_DIR" ] ; then
-      read -p "Warning: $SITE_DIR_ABS already exists. Do you want to continue [y/N]? " CONTINUE
-      if [ "$CONTINUE" != "y" ] ; then exit 0 ; fi
-   fi;
-
-   if [ ! -e "$SITE_DIR" ] ; then
-      echo "Creating directory $SITE_DIR_ABS"
-      mkdir -p "$SITE_DIR"
-      chmod 755 "$SITE_DIR"
-   fi;
+serve_help_docs () {
+   echo "Starting help server ..."
+   sleep 1
+   hugo serve --buildExpired --disableLiveReload --port 1414 1>/dev/null &
 }
 
 echo "Welcome to the After Dark quick installer. Press CTRL-C at any time to abort."
 
-create_site_dir ${1}
+validate_hugo
+create_site_dir "$1"
 create_site
 download_theme
-download_module
+update_archetypes
+download_module "fractal-forest"
 configure_theme
-create_example_post
-serve_site_maybe
+generate_help_docs
+serve_help_docs
 
-echo "Installation completed successfully!"
-echo "Your new site was created in $SITE_DIR_ABS."
-echo "Run 'cd $SITE_DIR && hugo serve --buildDrafts' to serve it."
+YELLOW='\033[0;33m'
+NC='\033[0m'
+
+echo "Installation successful!"
+echo "Site created in $SITE_DIR_ABS"
+echo "Help server started at http://localhost:1414/"
+echo "To stop it run \"kill \$(ps aux | awk '/[h]ugo.*1414/ {print \$2}')\"."
+echo "To update and start it again run \"./themes/after-dark/bin/help\"."
+printf "${YELLOW}Run \"cd $SITE_DIR && hugo serve\" to start your site.${NC}\n"
 echo "Thank you for choosing After Dark."
